/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package backend;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
/**
 *
 * @author USER
 */
public class Login extends javax.swing.JFrame {
   private String loggedInUser;
    private String loggedNamaUser;
    private String loggedAlamatUser;
    private String loggedNoTelpUser;
    private String loggedEmailUser;
    private String loggedUsernameUser;
    
     int xx,xy;
    
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        link_register = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(930, 650));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_username.setBorder(null);
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 448, 210, 20));

        txt_password.setBorder(null);
        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 486, 210, 20));

        btn_login.setContentAreaFilled(false);

        btn_login.setBorderPainted(false);
        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Button Login.png"))); // NOI18N
        btn_login.setContentAreaFilled(false);
        btn_login.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Button Select Login.png"))); // NOI18N
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        getContentPane().add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(396, 520, 290, 30));

        link_register.setContentAreaFilled(false);

        link_register.setBorderPainted(false);
        link_register.setBackground(new java.awt.Color(242, 242, 242));
        link_register.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Link Register.png"))); // NOI18N
        link_register.setBorder(null);
        link_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                link_registerActionPerformed(evt);
            }
        });
        getContentPane().add(link_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 560, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Login.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
           String Username, Password, passDB, query;
String SUrl, user, password;

SUrl = "jdbc:mysql://localhost:3306/brobets"; 
user = "root"; 
password = "";

Username = txt_username.getText();
Password = txt_password.getText();

if (Username.isEmpty()) {
    JOptionPane.showMessageDialog(new JFrame(), "Username tidak boleh kosong", "Error", JOptionPane.ERROR_MESSAGE);
    return;
} else if (Password.isEmpty()) {
    JOptionPane.showMessageDialog(new JFrame(), "Password tidak boleh kosong", "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

try {
    Class.forName("com.mysql.cj.jdbc.Driver");
    Connection conn = DriverManager.getConnection(SUrl, user, password);
    query = "SELECT * FROM pengguna WHERE nama_pengguna = ?"; // Perbaiki nama tabel dan kolom

    PreparedStatement s = conn.prepareStatement(query);
    s.setString(1, Username);

    ResultSet pw = s.executeQuery();

    if (pw.next()) {
        passDB = pw.getString("password");  // Sesuaikan nama kolom
        String Id = pw.getString("id_pengguna");
        String nama = pw.getString("nama_lengkap");
        String Alamat = pw.getString("alamat");
        String notelp = pw.getString("no_hp");
        String NamaUs = pw.getString("nama_pengguna");
        String Email = pw.getString("email");
        String role = pw.getString("role"); // Ambil role dari database

        if (Password.equals(passDB)) {
            loggedInUser = Id;
            loggedNamaUser = nama;
            loggedAlamatUser = Alamat;
            loggedNoTelpUser = notelp;
            loggedUsernameUser = NamaUs;
            loggedEmailUser = Email;

          if (role.equals("Admin")) {
                JOptionPane.showMessageDialog(new JFrame(), "Login berhasil sebagai Admin", "Success", JOptionPane.INFORMATION_MESSAGE);
                MenuDashPeg adminPage = new MenuDashPeg();
                adminPage.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(new JFrame(), "Login berhasil sebagai Pegawai", "Success", JOptionPane.INFORMATION_MESSAGE);
                DashPeg pegawaiPage = new DashPeg();
                pegawaiPage.setVisible(true);
            }
            
            this.dispose(); 
            
        } else {
            JOptionPane.showMessageDialog(new JFrame(), "Password salah", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(new JFrame(), "Username atau Password salah", "Error", JOptionPane.ERROR_MESSAGE);
    }

    conn.close();
    txt_password.setText("");

} catch (Exception e) {
    System.out.println("Error: " + e.getMessage());
    JOptionPane.showMessageDialog(new JFrame(), "Terjadi kesalahan saat masuk", "Error", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btn_loginActionPerformed

    private void link_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_link_registerActionPerformed
        // TODO add your handling code here:
        Register register = new Register();
        register.setVisible(true);
    }//GEN-LAST:event_link_registerActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
         xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
       int y = evt.getYOnScreen();
       this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton link_register;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
