/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package backend;

import java.awt.CardLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
/**
 *
 * @author HP
 */
public class MenuUser extends javax.swing.JPanel {

    /**
     * Creates new form MenuUser
     */
    public MenuUser() {
        initComponents();
        txt_password.setText("Masukkan Password");
        txt_password.setEchoChar((char) 0); 

        try {
            loadDataFromDatabase();
        } catch (Exception e) {
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        page_main = new javax.swing.JPanel();
        page_user = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btn_search = new javax.swing.JButton();
        txt_search = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btn_tambah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_user = new custom.JTable_custom();
        page_tambah = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        form_tambah = new javax.swing.JPanel();
        rbAdmin = new javax.swing.JRadioButton();
        rbPegawai = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_alamat = new javax.swing.JTextArea();
        txt_password = new javax.swing.JPasswordField();
        btn_password = new javax.swing.JCheckBox();
        txt_username = new javax.swing.JTextField();
        txt_telp = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btn_simpan = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        page_ubah = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        form_ubah = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txt_alamat1 = new javax.swing.JTextArea();
        btn_password1 = new javax.swing.JCheckBox();
        txt_password1 = new javax.swing.JPasswordField();
        txt_username1 = new javax.swing.JTextField();
        txt_telp1 = new javax.swing.JTextField();
        txt_email1 = new javax.swing.JTextField();
        txt_nama1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btn_update = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        page_main.setBackground(new java.awt.Color(255, 244, 232));
        page_main.setLayout(new java.awt.CardLayout());

        page_user.setBackground(new java.awt.Color(255, 244, 232));
        page_user.setForeground(new java.awt.Color(230, 230, 230));
        page_user.setPreferredSize(new java.awt.Dimension(836, 666));
        page_user.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user/Data User Judul.png"))); // NOI18N
        page_user.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 27, 250, 37));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Group 74.png"))); // NOI18N
        page_user.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 27, 41, 37));

        btn_search.setContentAreaFilled(false);

        btn_search.setBorderPainted(false);
        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/penyewaan/Button Search.png"))); // NOI18N
        btn_search.setBorder(null);
        btn_search.setContentAreaFilled(false);
        btn_search.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/penyewaan/Button Search Select.png"))); // NOI18N
        page_user.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 50, 40));

        txt_search.setBackground(new java.awt.Color(238, 236, 227));
        txt_search.setBorder(null);
        page_user.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 181, 290, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/penyewaan/Search.png"))); // NOI18N
        page_user.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 410, -1));

        btn_tambah.setContentAreaFilled(false);

        btn_tambah.setBorderPainted(false);
        btn_tambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user/Tambah user.png"))); // NOI18N
        btn_tambah.setBorder(null);
        btn_tambah.setContentAreaFilled(false);
        btn_tambah.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user/Tambah user gelap.png"))); // NOI18N
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        page_user.add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 210, 50));

        btn_hapus.setContentAreaFilled(false);
        btn_hapus.setBorderPainted(false);
        btn_hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user/Hapus user.png"))); // NOI18N
        btn_hapus.setBorder(null);
        btn_hapus.setContentAreaFilled(false);
        btn_hapus.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user/Hapus user gelap.png"))); // NOI18N
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        page_user.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, -1, 40));

        btn_ubah.setContentAreaFilled(false);

        btn_ubah.setBorderPainted(false);
        btn_ubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user/Ubah user.png"))); // NOI18N
        btn_ubah.setBorder(null);
        btn_ubah.setContentAreaFilled(false);
        btn_ubah.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user/Ubah user gelap.png"))); // NOI18N
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });
        page_user.add(btn_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, -1, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/penyewaan/BG Button.png"))); // NOI18N
        page_user.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 720, 65));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Group 28.png"))); // NOI18N
        page_user.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, 69));

        jLabel27.setText("Username");
        page_user.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, -1, 20));

        tb_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, ""},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Email", "Alamat", "No_HP", "Username", "Role", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_user);

        page_user.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 730, 370));

        page_main.add(page_user, "card2");

        page_tambah.setBackground(new java.awt.Color(255, 244, 232));
        page_tambah.setPreferredSize(new java.awt.Dimension(836, 666));
        page_tambah.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user/Tambah User Judul.png"))); // NOI18N
        page_tambah.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 27, 312, 37));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Group 74.png"))); // NOI18N
        page_tambah.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 27, 41, 37));

        form_tambah.setBackground(new java.awt.Color(255, 244, 232));
        form_tambah.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(rbAdmin);
        rbAdmin.setForeground(new java.awt.Color(255, 244, 232));
        rbAdmin.setText("Admin");
        rbAdmin.setBorder(null);
        rbAdmin.setContentAreaFilled(false);
        form_tambah.add(rbAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 405, -1, -1));

        buttonGroup1.add(rbPegawai);
        rbPegawai.setForeground(new java.awt.Color(255, 244, 232));
        rbPegawai.setText("Pegawai");
        rbPegawai.setBorder(null);
        rbPegawai.setContentAreaFilled(false);
        form_tambah.add(rbPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 405, -1, -1));

        jScrollPane3.setBorder(null);

        txt_alamat.setText("Masukkan Alamat"); txt_alamat.setForeground(Color.GRAY);
        txt_alamat.setBackground(new java.awt.Color(255, 244, 232));
        txt_alamat.setColumns(20);
        txt_alamat.setLineWrap(true);
        txt_alamat.setRows(5);
        txt_alamat.setBorder(null);
        txt_alamat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_alamatFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_alamatFocusLost(evt);
            }
        });
        jScrollPane3.setViewportView(txt_alamat);

        form_tambah.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 210, 430, 80));

        txt_password.setText("Masukkan Password"); txt_password.setForeground(Color.GRAY);
        txt_password.setBackground(new java.awt.Color(255, 244, 232));
        txt_password.setBorder(null);
        txt_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_passwordFocusLost(evt);
            }
        });
        form_tambah.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 357, 400, 30));

        btn_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_passwordActionPerformed(evt);
            }
        });
        form_tambah.add(btn_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 363, -1, -1));

        txt_username.setText("Masukkan Username"); txt_username.setForeground(Color.GRAY);
        txt_username.setBackground(new java.awt.Color(255, 244, 232));
        txt_username.setBorder(null);
        txt_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_usernameFocusLost(evt);
            }
        });
        form_tambah.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 309, 430, 30));

        txt_telp.setText("Masukkan Nomor Telepon"); txt_telp.setForeground(Color.GRAY);
        txt_telp.setBackground(new java.awt.Color(255, 244, 232));
        txt_telp.setBorder(null);
        txt_telp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_telpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_telpFocusLost(evt);
            }
        });
        form_tambah.add(txt_telp, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 161, 430, 30));

        txt_email.setText("Masukkan Email"); txt_email.setForeground(Color.GRAY);
        txt_email.setBackground(new java.awt.Color(255, 244, 232));
        txt_email.setBorder(null);
        txt_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_emailFocusLost(evt);
            }
        });
        form_tambah.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 113, 430, 30));

        txt_nama.setText("Masukkan Nama Lengkap"); txt_nama.setForeground(Color.GRAY);
        txt_nama.setBackground(new java.awt.Color(255, 244, 232));
        txt_nama.setBorder(null);
        txt_nama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_namaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_namaFocusLost(evt);
            }
        });
        form_tambah.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 65, 430, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user/Form tambah user.png"))); // NOI18N
        form_tambah.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 490));

        page_tambah.add(form_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 750, 490));

        btn_simpan.setContentAreaFilled(false);

        btn_simpan.setBorderPainted(false);
        btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user/Simpan.png"))); // NOI18N
        btn_simpan.setBorder(null);
        btn_simpan.setContentAreaFilled(false);
        btn_simpan.setPreferredSize(new java.awt.Dimension(100, 35));
        btn_simpan.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user/Simpan gelap.png"))); // NOI18N
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        page_tambah.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 580, 100, 40));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Group 28.png"))); // NOI18N
        page_tambah.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, 69));

        jLabel31.setText("Username");
        page_tambah.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, -1, 20));

        page_main.add(page_tambah, "card3");

        page_ubah.setBackground(new java.awt.Color(255, 244, 232));
        page_ubah.setPreferredSize(new java.awt.Dimension(836, 666));
        page_ubah.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user/Data User Judul.png"))); // NOI18N
        page_ubah.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 27, 312, 37));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Group 74.png"))); // NOI18N
        page_ubah.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 27, 41, 37));

        form_ubah.setBackground(new java.awt.Color(255, 244, 232));
        form_ubah.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane4.setBorder(null);

        txt_alamat1.setBackground(new java.awt.Color(255, 244, 232));
        txt_alamat1.setColumns(20);
        txt_alamat1.setLineWrap(true);
        txt_alamat1.setRows(5);
        txt_alamat1.setBorder(null);
        txt_alamat1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_alamat1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_alamat1FocusLost(evt);
            }
        });
        jScrollPane4.setViewportView(txt_alamat1);

        form_ubah.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 229, 430, 80));

        btn_password1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_password1ActionPerformed(evt);
            }
        });
        form_ubah.add(btn_password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 382, -1, -1));

        txt_password.setText("Masukkan Password"); txt_password.setForeground(Color.GRAY);
        txt_password1.setBackground(new java.awt.Color(255, 244, 232));
        txt_password1.setBorder(null);
        txt_password1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_password1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_password1FocusLost(evt);
            }
        });
        form_ubah.add(txt_password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 376, 400, 30));

        txt_username1.setBackground(new java.awt.Color(255, 244, 232));
        txt_username1.setBorder(null);
        txt_username1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_username1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_username1FocusLost(evt);
            }
        });
        form_ubah.add(txt_username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 328, 430, 30));

        txt_telp1.setBackground(new java.awt.Color(255, 244, 232));
        txt_telp1.setBorder(null);
        txt_telp1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_telp1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_telp1FocusLost(evt);
            }
        });
        form_ubah.add(txt_telp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 180, 430, 30));

        txt_email1.setBackground(new java.awt.Color(255, 244, 232));
        txt_email1.setBorder(null);
        txt_email1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_email1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_email1FocusLost(evt);
            }
        });
        form_ubah.add(txt_email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 132, 430, 30));

        txt_nama1.setText("Masukkan Nama Lengkap"); txt_nama1.setForeground(Color.GRAY);
        txt_nama1.setBackground(new java.awt.Color(255, 244, 232));
        txt_nama1.setBorder(null);
        txt_nama1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_nama1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_nama1FocusLost(evt);
            }
        });
        form_ubah.add(txt_nama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 84, 430, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user/Form Ubah user.png"))); // NOI18N
        form_ubah.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 490));

        page_ubah.add(form_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 750, 490));

        btn_simpan.setContentAreaFilled(false);

        btn_simpan.setBorderPainted(false);
        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user/Update.png"))); // NOI18N
        btn_update.setBorder(null);
        btn_update.setContentAreaFilled(false);
        btn_update.setPreferredSize(new java.awt.Dimension(100, 35));
        btn_update.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/user/Update gelap.png"))); // NOI18N
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        page_ubah.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 580, 100, 40));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Group 28.png"))); // NOI18N
        page_ubah.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, 69));

        jLabel35.setText("Username");
        page_ubah.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, -1, 20));

        page_main.add(page_ubah, "card3");

        add(page_main, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        page_main.removeAll();
        page_main.add(page_tambah);
        page_main.repaint();
        page_main.revalidate();
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
    // Mendapatkan baris yang dipilih dari jTable1
    int PilihBaris = tb_user.getSelectedRow();
    if (PilihBaris == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Mendapatkan ID dari kolom pertama
    DefaultTableModel model = (DefaultTableModel) tb_user.getModel();
    String idUser = (String) model.getValueAt(PilihBaris, 0);

    // Konfirmasi penghapusan
    int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi", javax.swing.JOptionPane.YES_NO_OPTION);
    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    // Hapus data dari database
    String delete = "DELETE FROM pengguna WHERE id_pengguna = ?";

    try (Connection con = DriverManager.getConnection(url, user, DBpassword);
         PreparedStatement hapus = con.prepareStatement(delete)) {

        hapus.setString(1, idUser);
        int rowsAffected = hapus.executeUpdate();

        if (rowsAffected > 0) {
            // Hapus baris dari tabel
            model.removeRow(PilihBaris);
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus.", "Sukses", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Gagal menghapus data.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menghapus data: " + e.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
    String nama, email, alamat, no_HP, username, password;
        
    int PilihBaris = tb_user.getSelectedRow();
    if (PilihBaris == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data yang ingin diedit!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    DefaultTableModel model = (DefaultTableModel) tb_user.getModel();
    selectedIdUser = (String) model.getValueAt(PilihBaris, 0);  // Disimpan, tapi tidak diubah
    nama = (String) model.getValueAt(PilihBaris, 1);
    email = (String) model.getValueAt(PilihBaris, 2);
    alamat = (String) model.getValueAt(PilihBaris, 3);
    no_HP = (String) model.getValueAt(PilihBaris, 4);
    username = (String) model.getValueAt(PilihBaris, 5);
    password = (String) model.getValueAt(PilihBaris, 7);

    page_main.removeAll();
    page_main.add(page_ubah);
    page_main.repaint();
    page_main.revalidate();
    
    txt_nama1.setText(nama);
    txt_nama1.setForeground(Color.BLACK);
    txt_email1.setText(email);
    txt_email1.setForeground(Color.BLACK);
    txt_alamat1.setText(alamat);
    txt_alamat1.setForeground(Color.BLACK);
    txt_telp1.setText(no_HP);
    txt_telp1.setForeground(Color.BLACK);
    txt_username1.setText(username);
    txt_username1.setForeground(Color.BLACK);
    txt_password1.setText(password);
    txt_password1.setEchoChar('•');
    txt_password1.setForeground(Color.BLACK);
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
    String nama, email, no_hp, alamat, username, password, role = null, save;
    
    String idUser = generateIdOtomatis();
    nama = txt_nama.getText();
    email = txt_email.getText();
    no_hp = txt_telp.getText();
    alamat = txt_alamat.getText();
    username = txt_username.getText();
    password = new String(txt_password.getPassword());
    if (rbAdmin.isSelected()) {
    role = "admin";
    } else if (rbPegawai.isSelected()) {
    role = "pegawai";
    }
        
    if (
        nama.isEmpty() || nama.equals("Masukkan Nama Lengkap") ||
        email.isEmpty() || email.equals("Masukkan Email") ||
        no_hp.isEmpty() || no_hp.equals("Masukkan Nomor Telepon") ||
        alamat.isEmpty() || alamat.equals("Masukkan Alamat") ||
        username.isEmpty() || username.equals("Masukkan Username") ||
        password.isEmpty() || password.equals("Masukkan Password")
    ) {
        JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    save = "INSERT INTO pengguna (id_pengguna, nama_lengkap, email, alamat, no_hp, nama_pengguna, password, role) " +
                   "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
    
    try {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/brobets", "root", "");
        String CekUsername = "SELECT * FROM pengguna WHERE nama_pengguna = ?"; // cek usesrname
        PreparedStatement cekuser = con.prepareStatement(CekUsername);
        cekuser.setString(1, username);
        ResultSet rs = cekuser.executeQuery();

        if (rs.next()) {
            JOptionPane.showMessageDialog(this, "Username sudah digunakan, silakan pilih yang lain", "Error", JOptionPane.ERROR_MESSAGE);
            return; // berhrnti nyimpen
        }
        PreparedStatement simpan = con.prepareStatement(save);
        simpan.setString(1, idUser);
        simpan.setString(2, nama);
        simpan.setString(3, email);
        simpan.setString(4, alamat);
        simpan.setString(5, no_hp);
        simpan.setString(6, username);
        simpan.setString(7, password);
        simpan.setString(8, role);
   
        int result = simpan.executeUpdate();
        
        if (result > 0 ) {
            JOptionPane.showMessageDialog(this, "Pengguna berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            page_main.removeAll();
            page_main.add(page_user);
            page_main.repaint();
            page_main.revalidate();
            loadDataFromDatabase();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menambahkan pengguna!", "Error", JOptionPane.ERROR_MESSAGE);
            }
            con.close();
        
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Database Error" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
    String newNama, newEmail, newAlamat, newNo_HP, newUsername, newPassword, update;
    
    newNama = txt_nama1.getText().trim();
    newEmail = txt_email1.getText().trim();
    newAlamat = txt_alamat1.getText().trim();
    newNo_HP = txt_telp1.getText().trim();
    newUsername = txt_username1.getText().trim();
    newPassword = new String(txt_password1.getPassword()).trim();

    // Validasi input
    if (newNama.isEmpty() || newEmail.isEmpty() || newAlamat.isEmpty() || 
        newNo_HP.isEmpty() || newUsername.isEmpty() || newPassword.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Semua field harus diisi!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    update = "UPDATE pengguna SET nama_lengkap = ?, email = ?, alamat = ?, no_hp = ?, nama_pengguna = ?, password = ? WHERE id_pengguna = ?";

    try {
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/brobets", "root", "");
        String CekPengguna = "SELECT * FROM pengguna WHERE nama_pengguna = ? AND id_pengguna != ?";
        PreparedStatement cekpengguna = con.prepareStatement(CekPengguna);
        cekpengguna.setString(1, newUsername);
        cekpengguna.setString(2, selectedIdUser);
        ResultSet rs = cekpengguna.executeQuery();

        if (rs.next()) {
            JOptionPane.showMessageDialog(this, "Username sudah digunakan, silakan pilih yang lain", "Error", JOptionPane.ERROR_MESSAGE);
            return; // hentikan proses simpan
        }

        PreparedStatement ubah = con.prepareStatement(update);
        ubah.setString(1, newNama);
        ubah.setString(2, newEmail);
        ubah.setString(3, newAlamat);
        ubah.setString(4, newNo_HP);
        ubah.setString(5, newUsername);
        ubah.setString(6, newPassword);
        ubah.setString(7, selectedIdUser); // id hanya sebagai kunci WHERE

        int result = ubah.executeUpdate();
        
        if (result > 0) {
            JOptionPane.showMessageDialog(this, "Data berhasil diperbarui.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            page_main.removeAll();
            page_main.add(page_user);
            page_main.repaint();
            page_main.revalidate();
            loadDataFromDatabase();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal memperbarui data.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        con.close();

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Kesalahan: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void txt_namaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_namaFocusGained
        if (txt_nama.getText().equals("Masukkan Nama Lengkap")) {
            txt_nama.setText("");
            txt_nama.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_namaFocusGained

    private void txt_namaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_namaFocusLost
        if (txt_nama.getText().isEmpty()) {
            txt_nama.setText("Masukkan Nama Lengkap");
            txt_nama.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txt_namaFocusLost

    private void txt_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emailFocusGained
        if (txt_email.getText().equals("Masukkan Email")) {
            txt_email.setText("");
            txt_email.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_emailFocusGained

    private void txt_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emailFocusLost
        if (txt_email.getText().isEmpty()) {
            txt_email.setText("Masukkan Email");
            txt_email.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txt_emailFocusLost

    private void txt_telpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_telpFocusGained
        if (txt_telp.getText().equals("Masukkan Nomor Telepon")) {
            txt_telp.setText("");
            txt_telp.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_telpFocusGained

    private void txt_telpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_telpFocusLost
        if (txt_telp.getText().isEmpty()) {
            txt_telp.setText("Masukkan Nomor Telepon");
            txt_telp.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txt_telpFocusLost

    private void txt_alamatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_alamatFocusGained
        if (txt_alamat.getText().equals("Masukkan Alamat")) {
            txt_alamat.setText("");
            txt_alamat.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_alamatFocusGained

    private void txt_alamatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_alamatFocusLost
        if (txt_alamat.getText().isEmpty()) {
            txt_alamat.setText("Masukkan Alamat");
            txt_alamat.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txt_alamatFocusLost

    private void txt_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusGained
        if (txt_username.getText().equals("Masukkan Username")) {
            txt_username.setText("");
            txt_username.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_usernameFocusGained

    private void txt_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusLost
        if (txt_username.getText().isEmpty()) {
            txt_username.setText("Masukkan Username");
            txt_username.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txt_usernameFocusLost

    private void txt_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passwordFocusGained
        if (new String(txt_password.getPassword()).equals("Masukkan Password")) {
            txt_password.setText("");
            txt_password.setForeground(Color.BLACK);
            if (!btn_password.isSelected()) {
                txt_password.setEchoChar('•');
        }}
    }//GEN-LAST:event_txt_passwordFocusGained

    private void txt_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passwordFocusLost
        if (txt_password.getPassword().length == 0) {
            txt_password.setText("Masukkan Password");
            txt_password.setEchoChar((char) 0);
            txt_password.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txt_passwordFocusLost

    private void btn_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_passwordActionPerformed
        if (btn_password.isSelected()) {
            txt_password.setEchoChar((char) 0); // Menampilkan password
        } else {
            txt_password.setEchoChar('•'); // Menyembunyikan password
        }
    }//GEN-LAST:event_btn_passwordActionPerformed
// BATAS FIELD TAMBAH DAN UBAHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH
    private void btn_password1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_password1ActionPerformed
        if (btn_password1.isSelected()) {
            txt_password1.setEchoChar((char) 0); // Menampilkan password
        } else {
            txt_password1.setEchoChar('•'); // Menyembunyikan password
        }
    }//GEN-LAST:event_btn_password1ActionPerformed

    private void txt_nama1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nama1FocusGained
        if (txt_nama1.getText().equals("Masukkan Nama Lengkap")) {
            txt_nama1.setText("");
            txt_nama1.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_nama1FocusGained

    private void txt_nama1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nama1FocusLost
        if (txt_nama1.getText().isEmpty()) {
            txt_nama1.setText("Masukkan Nama Lengkap");
            txt_nama1.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txt_nama1FocusLost

    private void txt_email1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_email1FocusGained
        if (txt_email1.getText().equals("Masukkan Email")) {
            txt_email1.setText("");
            txt_email1.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_email1FocusGained

    private void txt_email1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_email1FocusLost
        if (txt_email1.getText().isEmpty()) {
            txt_email1.setText("Masukkan Email");
            txt_email1.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txt_email1FocusLost

    private void txt_telp1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_telp1FocusGained
        if (txt_telp1.getText().equals("Masukkan Nomor Telepon")) {
            txt_telp1.setText("");
            txt_telp1.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_telp1FocusGained

    private void txt_telp1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_telp1FocusLost
        if (txt_telp1.getText().isEmpty()) {
            txt_telp1.setText("Masukkan Nomor Telepon");
            txt_telp1.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txt_telp1FocusLost

    private void txt_alamat1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_alamat1FocusGained
        if (txt_alamat1.getText().equals("Masukkan Alamat")) {
            txt_alamat1.setText("");
            txt_alamat1.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_alamat1FocusGained

    private void txt_alamat1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_alamat1FocusLost
        if (txt_alamat1.getText().isEmpty()) {
            txt_alamat1.setText("Masukkan Alamat");
            txt_alamat1.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txt_alamat1FocusLost

    private void txt_username1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_username1FocusGained
        if (txt_username1.getText().equals("Masukkan Username")) {
            txt_username1.setText("");
            txt_username1.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txt_username1FocusGained

    private void txt_username1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_username1FocusLost
        if (txt_username1.getText().isEmpty()) {
            txt_username1.setText("Masukkan Username");
            txt_username1.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txt_username1FocusLost

    private void txt_password1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_password1FocusGained
        if (new String(txt_password1.getPassword()).equals("Masukkan Password")) {
            txt_password1.setText("");
            txt_password1.setForeground(Color.BLACK);
            if (!btn_password1.isSelected()) {
                txt_password1.setEchoChar('•');
        }}
    }//GEN-LAST:event_txt_password1FocusGained

    private void txt_password1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_password1FocusLost
        if (txt_password1.getPassword().length == 0) {
            txt_password1.setText("Masukkan Password");
            txt_password1.setEchoChar((char) 0);
            txt_password1.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txt_password1FocusLost
    
    String url = "jdbc:mysql://localhost:3306/brobets";
    String user = "root";
    String DBpassword = "";
        
    public String generateIdOtomatis() {
        String idBaru = "UR001";
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/brobets", "root", "");
            // 2. Ambil ID terakhir dari database
            String sql = "SELECT id_pengguna FROM pengguna ORDER BY id_pengguna DESC LIMIT 1";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            // 3. Generate ID baru
            if (rs.next()) {
                String lastId = rs.getString("id_pengguna"); // contoh: UR007
                int angka = Integer.parseInt(lastId.substring(2)); // ambil "007" jadi int 7
                angka++; // naik satu
                idBaru = String.format("UR%03d", angka); // jadi UR008
            }

            // 4. Tutup koneksi
            rs.close();
            ps.close();
            con.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal generate ID: " + e.getMessage());
        }

        return idBaru;
    }
    
    private void loadDataFromDatabase() throws java.sql.SQLException {
        String query = "SELECT * FROM pengguna";
        try (Connection con = DriverManager.getConnection(url, user, DBpassword);
             java.sql.Statement stmt = con.createStatement();
             java.sql.ResultSet rs = stmt.executeQuery(query)) {
             DefaultTableModel model = (DefaultTableModel) tb_user.getModel();
             model.setRowCount(0);

            while (rs.next()) {
                Object[] row = {
                rs.getString("id_pengguna"),
                rs.getString("nama_lengkap"),
                rs.getString("email"),
                rs.getString("alamat"),
                rs.getString("no_hp"),
                rs.getString("nama_pengguna"),
                rs.getString("role"),
                rs.getString("password"),
                };
                model.addRow(row);
            }
        }    
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hapus;
    private javax.swing.JCheckBox btn_password;
    private javax.swing.JCheckBox btn_password1;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JButton btn_update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel form_tambah;
    private javax.swing.JPanel form_ubah;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel page_main;
    private javax.swing.JPanel page_tambah;
    private javax.swing.JPanel page_ubah;
    private javax.swing.JPanel page_user;
    private javax.swing.JRadioButton rbAdmin;
    private javax.swing.JRadioButton rbPegawai;
    private custom.JTable_custom tb_user;
    private javax.swing.JTextArea txt_alamat;
    private javax.swing.JTextArea txt_alamat1;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_email1;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nama1;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JPasswordField txt_password1;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_telp;
    private javax.swing.JTextField txt_telp1;
    private javax.swing.JTextField txt_username;
    private javax.swing.JTextField txt_username1;
    // End of variables declaration//GEN-END:variables
    private String selectedIdUser;
}

