/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package backend;

/**
 *
 * @author USER
 */
public class MenuDashPeg extends javax.swing.JPanel {

    /**
     * Creates new form MenuDashPeg
     */
    public MenuDashPeg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        page_dashpeg = new javax.swing.JPanel();
        card_pelanggan = new custom.panel2_custom();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        card_items = new custom.panel2_custom();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        card_penyewaan = new custom.panel2_custom();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        card_pengembalian = new custom.panel2_custom();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        card_stok = new custom.panel2_custom();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        page_dashpeg.setBackground(new java.awt.Color(255, 244, 232));

        card_pelanggan.setBackground(new java.awt.Color(255, 244, 232));
        card_pelanggan.setRoundBottomLeft(10);
        card_pelanggan.setRoundBottomRight(10);
        card_pelanggan.setRoundTopLeft(10);
        card_pelanggan.setRoundTopRight(10);
        card_pelanggan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Line 232.png"))); // NOI18N
        card_pelanggan.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 240, 10));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Vector.png"))); // NOI18N
        card_pelanggan.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 30, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Ellipse 13.png"))); // NOI18N
        card_pelanggan.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 50, 60));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/PELANGGAN.png"))); // NOI18N
        card_pelanggan.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Rectangle 132.png"))); // NOI18N
        card_pelanggan.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        card_items.setBackground(new java.awt.Color(255, 244, 232));
        card_items.setRoundBottomLeft(10);
        card_items.setRoundBottomRight(10);
        card_items.setRoundTopLeft(10);
        card_items.setRoundTopRight(10);
        card_items.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Line 232.png"))); // NOI18N
        card_items.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 240, 10));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Vector2.png"))); // NOI18N
        card_items.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 30, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Ellipse 13.png"))); // NOI18N
        card_items.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 50, 60));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/ITEMS.png"))); // NOI18N
        card_items.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Rectangle 132.png"))); // NOI18N
        card_items.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        card_penyewaan.setBackground(new java.awt.Color(255, 244, 232));
        card_penyewaan.setRoundBottomLeft(10);
        card_penyewaan.setRoundBottomRight(10);
        card_penyewaan.setRoundTopLeft(10);
        card_penyewaan.setRoundTopRight(10);
        card_penyewaan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Line 232.png"))); // NOI18N
        card_penyewaan.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 240, 10));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Vector-2.png"))); // NOI18N
        card_penyewaan.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 30, 40));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Ellipse 13.png"))); // NOI18N
        card_penyewaan.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 50, 60));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/PENYEWAAN.png"))); // NOI18N
        card_penyewaan.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Rectangle 132.png"))); // NOI18N
        card_penyewaan.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        card_pengembalian.setBackground(new java.awt.Color(255, 244, 232));
        card_pengembalian.setRoundBottomLeft(10);
        card_pengembalian.setRoundBottomRight(10);
        card_pengembalian.setRoundTopLeft(10);
        card_pengembalian.setRoundTopRight(10);
        card_pengembalian.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Line 232.png"))); // NOI18N
        card_pengembalian.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 240, 10));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Vector3.png"))); // NOI18N
        card_pengembalian.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 40, 40));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Ellipse 13.png"))); // NOI18N
        card_pengembalian.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 50, 60));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/PENGEMBALIAN.png"))); // NOI18N
        card_pengembalian.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 20));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Rectangle 132.png"))); // NOI18N
        card_pengembalian.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 120));

        card_stok.setBackground(new java.awt.Color(255, 244, 232));
        card_stok.setRoundBottomLeft(10);
        card_stok.setRoundBottomRight(10);
        card_stok.setRoundTopLeft(10);
        card_stok.setRoundTopRight(10);
        card_stok.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Line 232.png"))); // NOI18N
        card_stok.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 240, 10));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Vector-1.png"))); // NOI18N
        card_stok.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 40, 40));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Ellipse 13.png"))); // NOI18N
        card_stok.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 50, 60));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/STOK MASUK.png"))); // NOI18N
        card_stok.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 20));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Rectangle 132.png"))); // NOI18N
        card_stok.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 120));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Group 76.png"))); // NOI18N

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Group 74.png"))); // NOI18N

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Group 28.png"))); // NOI18N

        jLabel19.setText("Username");

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Chart.png"))); // NOI18N

        javax.swing.GroupLayout page_dashpegLayout = new javax.swing.GroupLayout(page_dashpeg);
        page_dashpeg.setLayout(page_dashpegLayout);
        page_dashpegLayout.setHorizontalGroup(
            page_dashpegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(page_dashpegLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(page_dashpegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(page_dashpegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(page_dashpegLayout.createSequentialGroup()
                            .addComponent(card_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(card_items, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(card_penyewaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, page_dashpegLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(card_pengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(card_stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(128, 128, 128)))
                    .addGroup(page_dashpegLayout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(244, 244, 244)
                        .addComponent(jLabel19)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel18)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, page_dashpegLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        page_dashpegLayout.setVerticalGroup(
            page_dashpegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(page_dashpegLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(page_dashpegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(page_dashpegLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(page_dashpegLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(page_dashpegLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(page_dashpegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(card_pelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card_items, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card_penyewaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(page_dashpegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(card_pengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(card_stok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        add(page_dashpeg, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private custom.panel2_custom card_items;
    private custom.panel2_custom card_pelanggan;
    private custom.panel2_custom card_pengembalian;
    private custom.panel2_custom card_penyewaan;
    private custom.panel2_custom card_stok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel page_dashpeg;
    // End of variables declaration//GEN-END:variables
}
