/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package backend;

import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author HP
 */
public class MenuDashAdm extends javax.swing.JPanel {

    /**
     * Creates new form MenuDashAdm
     */
    public MenuDashAdm() {
        initComponents();
        label_username.setText(Login.Session.getUsername());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        page_dashadm = new javax.swing.JPanel();
        card_user = new custom.panel2_custom();
        user = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        card_omset = new custom.panel2_custom();
        omset = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        label_username = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        page_dashadm.setBackground(new java.awt.Color(255, 244, 232));
        page_dashadm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        card_user.setBackground(new java.awt.Color(255, 244, 232));
        card_user.setRoundBottomLeft(10);
        card_user.setRoundBottomRight(10);
        card_user.setRoundTopLeft(10);
        card_user.setRoundTopRight(10);
        card_user.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user.setName(""); // NOI18N
        card_user.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 70, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Line 232.png"))); // NOI18N
        card_user.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 240, 10));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashadm/USER LOGO.png"))); // NOI18N
        card_user.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 19, 30, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Ellipse 13.png"))); // NOI18N
        card_user.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 50, 60));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashadm/DATA USER_1.png"))); // NOI18N
        card_user.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Rectangle 132.png"))); // NOI18N
        card_user.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        page_dashadm.add(card_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 91, -1, -1));

        card_omset.setBackground(new java.awt.Color(255, 244, 232));
        card_omset.setRoundBottomLeft(10);
        card_omset.setRoundBottomRight(10);
        card_omset.setRoundTopLeft(10);
        card_omset.setRoundTopRight(10);
        card_omset.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        omset.setName(""); // NOI18N
        card_omset.add(omset, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 70, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Line 232.png"))); // NOI18N
        card_omset.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 240, 10));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashadm/OMSET LOGO.png"))); // NOI18N
        card_omset.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 20, 40, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Ellipse 13.png"))); // NOI18N
        card_omset.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 50, 60));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashadm/OMSET.png"))); // NOI18N
        card_omset.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Rectangle 132.png"))); // NOI18N
        card_omset.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        page_dashadm.add(card_omset, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 91, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashadm/OWNER DASH.png"))); // NOI18N
        page_dashadm.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 27, 312, 37));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Group 74.png"))); // NOI18N
        page_dashadm.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 27, 41, 37));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Group 28.png"))); // NOI18N
        page_dashadm.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, 69));

        label_username.setText("Username");
        page_dashadm.add(label_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, -1, 20));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Chart.png"))); // NOI18N
        page_dashadm.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 403, 739, 242));

        add(page_dashadm, "card2");
    }// </editor-fold>//GEN-END:initComponents
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private custom.panel2_custom card_omset;
    private custom.panel2_custom card_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel label_username;
    private javax.swing.JLabel omset;
    private javax.swing.JPanel page_dashadm;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
