
package backend;


import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;


public class MenuPelanggan extends javax.swing.JPanel {

 JTable table;
    DefaultTableModel model;   
    
    public MenuPelanggan() {
        initComponents();
         loadDataTabel();
         label_username.setText(Login.Session.getUsername());
    }

    private void loadDataTabel() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Pelanggan");
    model.addColumn("Nama");
    model.addColumn("No HP");
    model.addColumn("Poin");
    model.addColumn("Status");

    jTable_custom1.setModel(model);

    Koneksi koneksi = new Koneksi();
    koneksi.config();

    try {
        Connection conn = koneksi.getConnection();
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery("SELECT * FROM pelanggan");

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_pelanggan"),
                rs.getString("nama_pelanggan"),
                rs.getString("no_hp"),
                rs.getInt("poin"),
                rs.getString("status")
            });
        }

        rs.close();
        st.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal mengambil data: " + e.getMessage());
    }
}



    private void hapusData() {
    int selectedRow = jTable_custom1.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih baris yang ingin dinonaktifkan!");
        return;
    }

    String idPelanggan = jTable_custom1.getValueAt(selectedRow, 0).toString();

    int konfirmasi = JOptionPane.showConfirmDialog(this,
            "Yakin ingin menonaktifkan pelanggan dengan ID: " + idPelanggan + "?",
            "Konfirmasi",
            JOptionPane.YES_NO_OPTION);

    if (konfirmasi == JOptionPane.YES_OPTION) {
        try {
            Koneksi koneksi = new Koneksi();
            koneksi.config();
            Connection conn = koneksi.getConnection();

            String sql = "UPDATE pelanggan SET status='nonaktif' WHERE id_pelanggan=?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, idPelanggan);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "Pelanggan dinonaktifkan!");
            loadDataTabel();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal: " + e.getMessage());
        }
    }
}

    private void aktifkanKembali() {
    int selectedRow = jTable_custom1.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih baris yang ingin diaktifkan kembali!");
        return;
    }

    String idPelanggan = jTable_custom1.getValueAt(selectedRow, 0).toString();

    try {
        Koneksi koneksi = new Koneksi();
        koneksi.config();
        Connection conn = koneksi.getConnection();

        String sql = "UPDATE pelanggan SET status='aktif' WHERE id_pelanggan=?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, idPelanggan);
        ps.executeUpdate();

        JOptionPane.showMessageDialog(this, "Pelanggan diaktifkan kembali!");
        loadDataTabel();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal mengaktifkan kembali: " + e.getMessage());
    }
}



    private void cariData() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("ID Pelanggan");
    model.addColumn("Nama");
    model.addColumn("No HP");
    model.addColumn("Poin");

    String keyword = txt_search.getText(); // ambil teks dari field pencarian

    try {
        Koneksi koneksi = new Koneksi();
        koneksi.config();
        Connection conn = koneksi.getConnection();

        String query = "SELECT * FROM pelanggan WHERE id_pelanggan LIKE ? OR nama_pelanggan LIKE ? OR no_hp LIKE ?";
        PreparedStatement ps = conn.prepareStatement(query);
        ps.setString(1, "%" + keyword + "%");
        ps.setString(2, "%" + keyword + "%");
        ps.setString(3, "%" + keyword + "%");

        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_pelanggan"),
                rs.getString("nama_pelanggan"),
                rs.getString("no_hp"),
                rs.getInt("poin")
            });
        }

        jTable_custom1.setModel(model);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal mencari data: " + e.getMessage());
    }
}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        page_main = new javax.swing.JPanel();
        page_penyewaan = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btn_search = new javax.swing.JButton();
        txt_search = new javax.swing.JTextField();
        btn_aktif = new javax.swing.JButton();
        btn_nonaktif = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        label_username = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_custom1 = new custom.JTable_custom();

        setLayout(new java.awt.CardLayout());

        page_main.setBackground(new java.awt.Color(255, 244, 232));
        page_main.setLayout(new java.awt.CardLayout());

        page_penyewaan.setBackground(new java.awt.Color(255, 244, 232));
        page_penyewaan.setForeground(new java.awt.Color(230, 230, 230));
        page_penyewaan.setPreferredSize(new java.awt.Dimension(836, 666));
        page_penyewaan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pelanggan/Data Pelanggan.png"))); // NOI18N
        page_penyewaan.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 27, 320, 37));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Group 74.png"))); // NOI18N
        page_penyewaan.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 27, 41, 37));

        btn_search.setContentAreaFilled(false);

        btn_search.setBorderPainted(false);
        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/penyewaan/Button Search.png"))); // NOI18N
        btn_search.setBorder(null);
        btn_search.setContentAreaFilled(false);
        btn_search.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/penyewaan/Button Search Select.png"))); // NOI18N
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        page_penyewaan.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 118, 60, 50));

        txt_search.setBackground(new java.awt.Color(238, 236, 227));
        txt_search.setBorder(null);
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        page_penyewaan.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 133, 240, 20));

        btn_aktif.setContentAreaFilled(false);
        btn_aktif.setBorderPainted(false);
        btn_aktif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pelanggan/Button Aktif.png"))); // NOI18N
        btn_aktif.setToolTipText("");
        btn_aktif.setBorder(null);
        btn_aktif.setContentAreaFilled(false);
        btn_aktif.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pelanggan/Button Aktif Select.png"))); // NOI18N
        btn_aktif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aktifActionPerformed(evt);
            }
        });
        page_penyewaan.add(btn_aktif, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, -1, 40));

        btn_nonaktif.setContentAreaFilled(false);
        btn_nonaktif.setBorderPainted(false);
        btn_nonaktif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pelanggan/Button Nonaktif.png"))); // NOI18N
        btn_nonaktif.setBorder(null);
        btn_nonaktif.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pelanggan/Button Nonaktif Select.png"))); // NOI18N
        btn_nonaktif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nonaktifActionPerformed(evt);
            }
        });
        page_penyewaan.add(btn_nonaktif, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, -1, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pelanggan/Fitur Search.png"))); // NOI18N
        page_penyewaan.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 720, 65));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashpeg/Group 28.png"))); // NOI18N
        page_penyewaan.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, 69));

        label_username.setText("Username");
        page_penyewaan.add(label_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, -1, 20));

        jTable_custom1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_custom1);

        page_penyewaan.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 730, 400));

        page_main.add(page_penyewaan, "card2");

        add(page_main, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nonaktifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nonaktifActionPerformed
        // TODO add your handling code here:
        hapusData();
    }//GEN-LAST:event_btn_nonaktifActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        cariData();
    }//GEN-LAST:event_btn_searchActionPerformed

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void btn_aktifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aktifActionPerformed
        // TODO add your handling code here:
         aktifkanKembali();
    }//GEN-LAST:event_btn_aktifActionPerformed




    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aktif;
    private javax.swing.JButton btn_nonaktif;
    private javax.swing.JButton btn_search;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JScrollPane jScrollPane1;
    private custom.JTable_custom jTable_custom1;
    private javax.swing.JLabel label_username;
    private javax.swing.JPanel page_main;
    private javax.swing.JPanel page_penyewaan;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
